wordpressUsername: admin
wordpressPassword: "AdminTCG2024!"
wordpressEmail: admin@tcg.local
wordpressBlogName: "TCG Lab"

# MariaDB externo (chart de MariaDB desplegado por separado)
mariadb:
  enabled: false

externalDatabase:
  host: mariadb.apps.svc.cluster.local
  port: 3306
  user: wordpress
  password: "WpTCG2024!"
  database: wordpress

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: wordpress.tcg.local
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: tcg-ca-issuer

persistence:
  enabled: false            # sin PVC en lab

resources:
  requests:
    cpu: 100m
    memory: 256Mi
