- name: Crear usuario devops
  user:
    name: "{{ new_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes

- name: Crear directorio SSH
  file:
    path: "/home/{{ new_user }}/.ssh"
    state: directory
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: '0700'

- name: Copiar clave publica
  authorized_key:
    user: "{{ new_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Permitir sudo sin password
  copy:
    dest: "/etc/sudoers.d/{{ new_user }}"
    content: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'

- name: Verificar que devops puede hacer sudo
  command: id devops
  changed_when: false