[ansible]
ansible-control ansible_host=192.168.56.10 ansible_connection=local

[edge]
edge-gateway ansible_host=192.168.56.15

[kube_control_plane]
k8s-master ansible_host=192.168.56.11

[etcd]
k8s-master

[kube_node]
worker1 ansible_host=192.168.56.12
worker2 ansible_host=192.168.56.13
worker3 ansible_host=192.168.56.14

[k8s_cluster:children]
kube_control_plane
kube_node

[managed:children]
edge
k8s_cluster
