ansible_user: vagrant
new_user: devops

packages_common:
  - vim
  - curl
  - git
  - python3
  - python3-pip
  - software-properties-common

edge_external_iface: enp0s3        
edge_internal_iface: enp0s8       
ingress_ip: 192.168.56.14        
http_nodeport: 30080             
https_nodeport: 30443    